### ISSUE TITLE
Major app versions

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#1]
In order to get a good first product version done in a reasonable amount of time, we decided that the first major version of the application will focus on the being a first-class node runner. The second major version will then add wallet functionality.

<img width="900" alt="bitcoin-core-app-versions" src="https://user-images.githubusercontent.com/695901/135256753-af746d07-d851-44d0-b196-68f4e867bc0c.png">

An earlier idea was to have 3 major versions, with the app offering key locker functionality at V2. The idea was to allow any of the users devices to become a multisig signer and therefore promoting better security practices and adoption of multisig. We decided against it as it would make development more complex.

<img width="1325" alt="bitcoin-core-app-versions-1" src="https://user-images.githubusercontent.com/695901/135256719-2961ef31-9a39-45e9-aec6-9b27d6006070.png">

**Comment by Bosch-0** [comment]
Just to add, the V1: Node runner will be designed and developed on Desktop, Android and iOS prior to moving into V2: Wallet.

**Comment by GBKS** [comment]
This is covered in the [roadmap page](https://bitcoincore.app/roadmap/) of the design docs.
