### ISSUE TITLE
Set and document colors

### ISSUE THREAD

**Issue by jarolrod** [BitcoinDesign/Bitcoin-Core-App#12]
Can we document what colors will be used throughout the application. Also can we establish color themes for light and dark mode.

**Comment by Bosch-0** [comment]
It will be documented in this repo as well as live in the Figma design system: https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/?node-id=1%3A3

**Comment by GBKS** [comment]
Colors are now also covered in the design docs site, see #19.
