### ISSUE TITLE
App Version: Product Intro UI Suggestions

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Bitcoin-Core-App#13]
**Button height (screens 3-5)**
Increased for consistency

**Button corner radius:**
Increased to 10 to create a more friendly brand

**Network icon**
Suggestion

**Heading font weight**
To create more contrast with body/paragraph

**Right arrow on button**
To encourage movement through the process

**System status**
Indication of where the user is in the sign up process

**Block clock concept (see figma file)**

Link to Figma file:
https://www.figma.com/file/HcWzozFhthvArdABf97g4q/Bitcoin-Core---Intro-Walkthrough

**Comment by GBKS** [comment]
Mo, thanks for posting these. Really appreciate you going through this in detail.

I think you may have started with an older version of the onboarding flow. Have you seen [the screens on this Figma page](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App-Main?node-id=2643%3A66434)?

Regarding your rationale for the corner radius, you want to create a more friendly brand. Taking a step back, do you think that is a larger issue with the proposed experience that it is not approachable or friendly? So far, I think we've taken the approach of being very neutral brand/personality-wise, but I do think we should have a direction and some guidelines, even if it's subtle.

Can you give an explanation of the block clock concept? I see the "counting down" and "activated" states. Heads up that there is some fairly complicated, non-obvious logic in the block clock that has to do with how the Bitcoin network operates. Let me know if you want to talk through this sometime.

Something to consider with pagination in onboarding processes is that it's often not possible to know in advance how many pages there will be. Users might make decisions that add additional screens to click through. I am not 100% what will be the case for this application, as the onboarding flow might be very different for desktop and mobile.

**Comment by Mogashni** [comment]
Hi Christoph, Indeed those were the older files which I have commented on. The link with the new Figma designs is much nicer! I agree that the brand personality can be expanded on a bit more in terms of the look and feel. The users also feels and experiences the brand/brand personality the moment they land on the app and it adds to their psychology of how they interact with it from the start.

Clock concept: I re-designed the clock with larger thicker line more for accessibility, thinking of people who were perhaps starting at their screens at night or have lesser eyesight. I think the clock concept is a wonderful part of this design and seeing the new figma file it is a core element there.
