### ISSUE TITLE
Create an about page in Figma main file

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Bitcoin-Core-App#15]
A designer recently went into the file and thought that Christoph's working file was the current active designs which lead to some confusion / time wasted by the designer. 

To avoid this issue happening again, and be more clear about our design work, It would be handy to have an about page in the Figma main file that details what this project is, objectives, how the file works (designer working pages, master pages etc). 

Went ahead and created a page for this [here](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/?node-id=569%3A559). Added a template that we can populate with content as we go.

**Comment by GBKS** [comment]
I started working on a website for design documentation for this purpose, see #19. That should become the primary starting point for people before the Figma file.

I also moved the template page further down in the list of pages in Figma, as it was still filled with placeholder text.

**Comment by GBKS** [comment]
I removed the template as it sat there unpopulated for months. Instead added a very simple intro page that refers people to the [design docs](https://bitcoindesign.github.io/Bitcoin-Core-App/) (that were created since this issue was opened). Hope that address this a little bit.
