### ISSUE TITLE
Animated gif for the desktop layout of Bitcoin Core

### ISSUE THREAD

**Issue by Susritachatterjee2020** [BitcoinDesign/Bitcoin-Core-App#18]
Hello I am Susrita, currently in proposal round of summer of bitcoin and I want to contribute in the bitcoin core design project this summer. I have developed some animated gifs for the onboarding process ui and which can motivate a user to engage more with bitcoin. My main idea is to implement a sticker sample for every step the user reaches. 
![Getting started with bitcoin](https://user-images.githubusercontent.com/60474018/163704932-b1b90efa-39d6-494e-8209-ad1071d546ad.gif)
This gif is for the desktop layout of bitcoin core where users can start their journey with bitcoin
![Optimization and network strength of bitcoin](https://user-images.githubusercontent.com/60474018/163705066-f88f9f2e-9703-460d-81a4-9941cf08292a.gif)

This is for Optimization and network strength of bitcoin

Any kind feedback and suggestions and changes are most welcomed.

**Comment by GBKS** [comment]
Thanks for posting these. Illustrations can be helpful in helping users better understand certain concepts, especially in onboarding. Just as a heads up, this repo is for the Bitcoin Core App, not the [Summer of Bitcoin project](https://www.summerofbitcoin.org/project-ideas-details?recordId=recYhuCaSN7tQ3jKO), which is a more general rethinking of how the Bitcoin Core project/community presents itself.

As for feedback on the illustrations, I think it's a bit early to say. Once we start the project, we will have a better idea of what illustrations we need, what style is appropriate, etc. Generally, I think we should think very deliberate about the elements we use. What do bitcoin tires on a car communicate to a user? Beyond an illustration looking nice, it's best if they also communicate an idea that represents an aspect of bitcoin. For example, if we want the user to understand what a node is and how it connects to a network of other nodes, how can an illustration makes this easy to understand? There are some applications and products that are super obvious to users and illustrations can just be playful and convey a feeling. With bitcoin, we have a lot of complex ideas users should at least somewhat be able to make sense of, and illustrations can be super helpful tools in that regard.

Hope that's helpful. What do you think?

**Comment by GBKS** [comment]
Would love to see more animations in the application in the future. Going to close this for now, but let's open up new issues with specific animations that we need as we work through the designs.
