### ISSUE TITLE
Progressive security

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#2]
We had a discussion around how we can help users keep up with good security practices. For example, the value of their bitcoin grows over time, and a single-sig setup may not be appropriate anymore.

Some points:
- Encourage the user to follow best practices vs. enforce them via the UI?
- How do we know what is appropriate for the user? A small amount of funds to one person can be a lot to another person.

Some sample screens from a previous exploration around usable security.
<img width="1050" alt="security-center" src="https://user-images.githubusercontent.com/695901/135257601-609a1217-ae2d-4fb9-80d6-afacded60725.png">

**Comment by Bosch-0** [comment]
My suggestion from slack:

> I would just keep things simple and have a persistent notification present once the user has any amount of funds in the app. It could be a little more subtle than the design above as to not be too intrusive to the user. Maybe the user can be 'nudged' towards this notification every time they add more funds to the app so they are constantly reminded. I think it is too hard to assume what x amount of bitcoin is worth showing a notification for, especially for an application with a global audience.

**Comment by GBKS** [comment]
Going to close this old issue as the conversation is stale now. The concept is great, and we should apply it as continue working through the design.
