### ISSUE TITLE
Peers Indicator Design Suggestion: Signal Bars instead of Row of Dots

### ISSUE THREAD

**Issue by jarolrod** [BitcoinDesign/Bitcoin-Core-App#21]
@hebasto originally proposed a change to the `Peers Indicator` component here: https://github.com/bitcoin-core/gui-qml/pull/128
This is being opened to move the conversation on this possible design change into designer native channels.

The proposed change is to have the peers indicator be represented by signal bars instead of a row of dots.

hebasto implemented the design in this branch: https://github.com/hebasto/gui-qml/tree/220603-peers.ALT
Which upon running, presents the following: 
![hebasto-design](https://user-images.githubusercontent.com/23396902/175798665-958afc3c-fda0-4c51-8816-e9aba91446b3.png)

@GBKS also rendered this within the full block clock, which is not yet finished:
<img width="600" alt="christoph-design" src="https://user-images.githubusercontent.com/23396902/175798683-4ce3f205-4509-4310-8afd-82d6471edcfb.png">

**Comment by mouxdesign** [comment]
I like the blockclock design idea as a peers indicator from @GBKS as it fits in well with all the other already designed elements. With regards to the wording used within the peers indicator I am just wondering if there would be an alternative word to use for "blocktime".

Could there be perhaps another word we could use such as:

- Peers connection
- Connection

**Comment by jakubszwedo** [comment]
Isn't blocktime reffering to something else, namely the time block is mined (avg. 10 minutes)? Example [here](https://bitinfocharts.com/comparison/bitcoin-confirmationtime.html#3y) or [here ](https://blog.bitstamp.net/post/what-is-block-time/).

If I understand correctly and blocktime here reffers to block height, and there's another meaning for blocktime than used here, then it may be confusing for people already acquainted with those names

**Comment by Bosch-0** [comment]
Blocktime and block height are the same thing. But yes the bars are conveying peer connections and the number is the blocktime.

I have a bit of different suggestion for this part of the app. I think the blocktime / clock should stay focused on that single concept of blocktime and we should move this indicator to a 'network' icon in the top left that users can tap on and see various network based info. One detail being peers connected. The bars / dots don't convey the whole picture as the amount of peers you can connect to can vary and there is also inbound / outbound peer types. Other things could be if the user is using Tor / I2P, data your using, network type etc. Users could click on each variable to view more detailed info too (such as latency of peers). 

This icon could flash or have some kind of animation when it is still connecting / syncing etc. There is lots of info relevant to convey to users and a few dots or bars really doesn't offer that depth. 

If you check out the wallet Phoenix they have a network icon in the top left of their app when you log in which does something similar to what I've mentioned (says if you lightning peer is connected, if you electrum is connected, Tor if enabled etc).

**Comment by GBKS** [comment]
We have an onboarding screen that explains the block clock before users see it, to avoid confusion. 
![image](https://user-images.githubusercontent.com/695901/177274243-7d114996-532f-4f22-9b61-d409fb7051a8.png)

I think there's a good amount of depth that can be put into the dots. Seems to work just fine for wi-fi and cell connectivity on smart phones.
![image](https://user-images.githubusercontent.com/695901/177275884-6891d3d1-3ccf-4f38-944a-8b84a7b19b78.png)

The peer connection dots should be tappable and show an overlay with details, like this (content is not right, but this type of modal). I am not a big fan of what Phoenix does, it draws too much attention to the connectivity.
![image](https://user-images.githubusercontent.com/695901/177274609-522c26bf-4637-451c-ac17-3190b67cd644.png)

Similarly, tapping the Blocktime could potentially toggle through different information (if we can identify things people would want to see there).

There's also the concept of widgets, which are just a rough idea. We could let users pick a few widgets that are shown below the block clock and visualize different types of data. If someone really loves to see connections details at all times, this would allow them to do so.  
![image](https://user-images.githubusercontent.com/695901/177274847-8c8d8f46-bb75-4eb1-89ff-e80cb9a69393.png)

Some more explorations of widgets, heavily inspired by smart watch UIs (it is a block clock after all).
![image](https://user-images.githubusercontent.com/695901/177275062-07d06e56-6501-4226-a3dc-0c540106bb9d.png)

**Comment by GBKS** [comment]
Here's a sample visual for that peer connection overlay. Tells you in plain text what is happening, and you can pull up numerical stats if you want.

![image](https://user-images.githubusercontent.com/695901/177333419-30ac2355-c892-45fa-b1bb-383d1afaf9d6.png)

**Comment by GBKS** [comment]
I will close this issue as it has gone stale. A new one can be opened if there's more interest in exploring this.
