### ISSUE TITLE
Refine button component states

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#26]
Jakub has started designing interactive states (hover, selected, disabled, active...) for the button components, something we currently don't have, but need. These visual treatments can then ideally be ported to other components (like input fields).

[Figma link](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App?node-id=4714%3A108117)

**Comment by GBKS** [comment]
I [recorded an overview](https://youtu.be/-pxTm-msnpE) of where we are with some suggestions on what to do next.

**Comment by GBKS** [comment]
We spent our [last design jam session](https://github.com/BitcoinDesign/Meta/issues/370) ([recording](https://youtu.be/neeH7NOpHRc)) on this and came up with a good set of design decisions that we can move forward with. I will apply them to the design system next week.

**Comment by stackingsaunter** [comment]
I applied the changes we discussed to the main button component, so it automatically updated any button in the file.

**Comment by mouxdesign** [comment]
Adding in images of the various interactive states that we agreed on. We voted on the colors and details of the various interactive states and this is how the current designs were decided upon. 



![Image](https://user-images.githubusercontent.com/90313394/193273277-dabf76af-f789-42f5-88eb-05810b4ecdd0.jpg)



![Image](https://user-images.githubusercontent.com/90313394/193273291-476a03fb-66da-4149-a9c0-9a8c49daba01.jpg)

**Comment by GBKS** [comment]
I think we can close this issue. We had a nice group collaboration for these out (thank you), and the new Figma file now has a clean set of buttons and states to work with ([here](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=2643%3A83778)).
