### ISSUE TITLE
Wallet creation flow design discovery

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#27]
Creating wallets is likely to be part of first-use when wallet features roll out. It also defines a lot of how users interact with their wallets afterwards. We started design exploration in a few calls to better understand the features we need to support and how users may want to interact with them.

- [Design jam session #4 recording](https://www.youtube.com/watch?v=Bj7I3NKyP4Q)
- [User flows](https://www.figma.com/file/okfrefEpM4K4MKOaii1blo/Bitcoin-Core-User-Flow?node-id=0%3A1) in Figma
- [Christoph's exploration](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App?node-id=4827%3A110109) in Figma

Here's a suggested process for design discovery:

- We study the existing GUI, research and discuss the features so we understand them well
- The team decides what features to support for a first implementation, and what to do later
- We do broad design exploration, roughing out user flows, individual screens, etc
- We review it all together and make design decisions
- We create a final design for a first implementation

Some of these things can happen in parallel and people can work independently as they see fit. We can use the weekly calls to check-in with each other.

**Comment by mouxdesign** [comment]
We have done some further refinements to the wallet creation flow along with the help of the developers which helped alot with understanding any steps we might need to include.

At the moment for the MVP the focus is on the screen designs for the:
- Regular wallet
- View only wallet
- Multisig wallet

We have now some initial designs/useflows for each of the above user flows, more so for the Regular as well as the view only wallet. The multisig wallet we will look at in more detail as that has a higher level of complexity.

**Comment by mouxdesign** [comment]
Wallet creation screens have been further worked on. Adding in some initial designs for the regular wallet creation.



![Image](https://user-images.githubusercontent.com/90313394/193272197-878d6bd0-35dd-4a42-8c53-13093164c52f.jpg)

**Comment by GBKS** [comment]
Closing this issue as we now have the a proper milestone set up for this task via #62.
