### ISSUE TITLE
Send flow design discovery

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#28]
We started exploration how sending should work in multiple calls to better understand the features we need to support and how users may want to interact with them. It gets quite intricate, particularly across various wallet types.

- [Design jam session #2 recording](https://www.youtube.com/watch?v=i6gs54WIofM)
- [User flows](https://www.figma.com/file/okfrefEpM4K4MKOaii1blo/Bitcoin-Core-User-Flow?node-id=0%3A1) in Figma
- [Christoph's exploration](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App?node-id=4502%3A91679) of the overall flow in Figma
- [Gene's exploration](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App?node-id=4834%3A111193) on multi-sign signing in Figma

Here's a suggested process for design discovery:

- We study the existing GUI, research and discuss the features so we understand them well
- The team decides what features to support for a first implementation, and what to do later
- We do broad design exploration, roughing out user flows, individual screens, etc
- We review it all together and make design decisions
- We create a final design for a first implementation

Some of these things can happen in parallel and people can work independently as they see fit. We can use the weekly calls to check-in with each other.

**Comment by mouxdesign** [comment]
Updated the Send user flow (Multi sig 2 of 3) 

At the moment this userflow has the following steps:
1. Person 1 Creates transaction
2. Person 1 Signs  transaction
3. Person 1 Reviews transaction
4. Person 1 Sends transaction to Person 2
5. Person 2 Reviews transaction
6. Person 2 Signs transaction
7. Person 2 Confirms transaction

To understand/ask devs: 

- What happens to the transaction when it is live prior to being approved by person 2.
- What would the transaction screens look like when it is being signed by multiple people?
- Would there be a separate userflow for when the Multi-sig transaction is sign by people vs a person with different keys?

**Comment by GBKS** [comment]
Closing this issue as we now have the a proper milestone set up for this task via #65.
