### ISSUE TITLE
Pruning by default?

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#3]
Ideally, everyone runs full nodes, but this may not be possible on many smart phones. I see two questions:
- What options do we provide users?
- What does the app recommend (contextually), based on what it knows about its environment?

**Comment by moneyball** [comment]
I've run Bitcoin Core on an HTC Exodus (the phone ships with it). It working better than I'd imagined, but there remain serious limitations:
1. Core cannot run in the background so it cannot sync with the blockchain continuously. Instead, a user would have to open the app then wait an inordinately long time with the app in the foreground to sync. This alone is a showstopper.
2. It requires a large or unlimited data plan or only sync'ing over WiFi (ie >5 GB of monthly data just to download blocks)

**Comment by Bosch-0** [comment]
I have no solid data to back up this claim but I'd assume pruning by default would cater to majority of users needs whilst providing a better UX. As Bitcoin Core generally is not used in conjunction with Lightning (of which using a full archival node is preferred / necessary) there isn't really any downsides to running it in this manner. 

In saying this though users should have the option during on boarding to switch to being an archival node. For mobile this option should be more hidden whilst for desktop it can be displayed more prominently (as desktops are generally more powerful / have more storage). Will share some details around this in the onboarding issue https://github.com/BitcoinDesign/Bitcoin-Core-App/issues/5 soon. 

> Core cannot run in the background so it cannot sync with the blockchain continuously. 

Yes this will be an issue with the mobile app. I'm not too familiar with the logic behind how background run times work though but will pass this by the devs. 

If this is possible some things to consider

- Maybe the background sync only occurs if >50% battery or if plugged in. 
- Maybe it ONLY syncs when plugged in? People generally have their phone on charge at some point in the day and if we have traffic limits set (see comments below) it shouldn't take long to sync up to the tip. 
- Possibly run the mobile app in `-blocksonly` mode by default, this would make it quite trivial to keep up to latest tip without any serious bandwidth blockers. 

> ...requires a large or unlimited data plan or only sync'ing over WiFi (ie >5 GB of monthly data just to download blocks)

Some smart defaults / setting configurations to solve this could be:

- Run the mobile app in `-blocksonly` mode by default.
- Set a max daily upload limit by default (could be as small as 144mb / one days worth of blocks). 
- Disable listening so less relaying to other nodes is occurring by default. 
- Set max connected nodes - finding a sweet spot for this would be ideal as you wouldn't want this too small. 
- All these defaults could dynamically adjust based on if the user is on cellular or WiFi.

**Comment by moneyball** [comment]
"Maybe the background sync only occurs if >50% battery or if plugged in."

Again, there IS NO background sync. You can't sync in the background.

**Comment by GBKS** [comment]
Going to close this issue as it's old and stale. We give users two options (plus a custom one), and will try to tweak the logic to be smarter in future versions.

To the point about background syncing, this is resolved in the current Android build of the app. It creates a system notification widget that keeps the process alive. The app can continue to download blocks while in the background and the screen off.

A lot of data still needs to be downloaded, maybe this is something that can be fixed in the future, and can be discussed elsewhere.
