### ISSUE TITLE
Design disabled states

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#30]
@jarolrod has asked for disabled states for settings fields in the onboarding screens.

**Comment by jarolrod** [comment]
This has been implemented here: https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=6079%3A166436&t=wsGoRsOW4dqQanKL-4

**Comment by GBKS** [comment]
OK to tick this off then?

**Comment by GBKS** [comment]
Closing this issue. We have disabled states (and other states) now for UI elements. If one is missing, that can be handled via a new issue.
