### ISSUE TITLE
Add states and properties to input component and update designs

### ISSUE THREAD

**Issue by stackingsaunter** [BitcoinDesign/Bitcoin-Core-App#32]
We need to expand current input component with states we decided on the last design call (https://github.com/BitcoinDesign/Meta/issues/370), so it will automatically update the designs in the file. 

![Alternative input states](https://user-images.githubusercontent.com/68239231/188283233-5ea0beec-359e-44d3-92f3-7ae55630c2bf.png)

We can also add properties eg. label text property, input text properties, show/hide message under input, etc. Should we include icon here as well (as it is used in Send for example)?

Then we should review all inputs in the designs to see if all works well, where to change input variant to another state and also check if some inputs are detached and not a component.

This issue is also related to https://github.com/BitcoinDesign/Bitcoin-Core-App/issues/30

I may be able to do this in the next few days

**Comment by GBKS** [comment]
This issue has gone stale, let's close it and open up a new one if we need to. Our input field states are documented [in Figma here](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?type=design&node-id=2643%3A83770&mode=design&t=WawjRGdyOs6sUL0H-1).
