### ISSUE TITLE
Detail validation states for input fields

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#39]
What does it look like when a user enters "-2" for the amount of storage to use for block data?

We need to detail out the validation states for various types of input (number, min, max, non-empty, etc). Ideally we base this on broadly established standards that users are familiar with from browsers and operating systems.

**Comment by jarolrod** [comment]
I think this has been partially answered by showing an error message like here:https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=6079%3A166448&t=wsGoRsOW4dqQanKL-4

But also wonder If, for example, the value input field should vibrate in someway, clearly signaling along with the error message that the value entered is not acceptable.

**Comment by GBKS** [comment]
I know what type of effect you mean, it's like a "shaking head" type of motion. IMHO, the color and message are enough. These form screens are very functional in nature, and I'd focus animation effort on the primary screens.

A detail to maybe discuss is when validation is triggered - while typing, when the input field loses focus, or when a Save/Back button is pressed? While typing is the most immediate, but can also be unexpected/annoying as the layout changes abruptly.

**Comment by GBKS** [comment]
Closing this stale issue. Let's re-open or start a new one if needed.
