### ISSUE TITLE
Managing multiple wallets

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#4]
A UI can get pretty complex when there are options for managing multiple wallets. [Here's a video](https://youtu.be/H7Wlo6XH_FM) with some thoughts.

**Comment by Bosch-0** [comment]
We should add labels to differentiate V1 and V2 issues.

**Comment by GBKS** [comment]
This will be covered in milestone 1.3 (#61). Closing this issue.
