### ISSUE TITLE
Design a screen/alert to be shown where user confirms to visit external link

### ISSUE THREAD

**Issue by jarolrod** [BitcoinDesign/Bitcoin-Core-App#40]
We have several links in the gui where the user will be brought to an external site, mainly residing in the About settings:

<img width="752" alt="Screen Shot 2023-01-29 at 2 25 40 AM" src="https://user-images.githubusercontent.com/23396902/215311722-7876314c-ea9d-4826-a022-6493a499eb93.png">

When a user clicks on any of these, they should first be presented with a screen/alert where they will be able to make a conscious decision to actually visit the external site, or cancel the action.

**Comment by GBKS** [comment]
Here's a first draft ([Figma](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=6265%3A24513&t=zMt2NdeVGGnDAUL7-1)). This is the same style that we used for an error modal we came up with a while back.

![image](https://user-images.githubusercontent.com/695901/215438176-778181fa-da69-4f95-865a-92d40114605b.png)

**Comment by tilltonystark** [comment]
Hey!
Just wondering whether this issue is closed or not?

**Comment by GBKS** [comment]
The design is addressed, I don't think it is implemented in code yet though (just checked with one of the latest builds I have on my phone).

**Comment by tilltonystark** [comment]
Okayyy

**Comment by tilltonystark** [comment]
I have one more question. Would it be practical to make one of the buttons easier for the user by having a lower cognitive load than the other? Could we make one button secondary and the other tertiary to help guide them along?

**Comment by GBKS** [comment]
Sure thing. Here's a version with an orange button. Of course, then people are just a little more likely to just press the big visual button that draws their attention and be a little less intentional about their choice.

![image](https://user-images.githubusercontent.com/695901/232466077-d8824c9d-fa1c-49e7-ab84-bc87319da2ca.png)

**Comment by tilltonystark** [comment]
Yeah, this will help the user in making the decision. Great!!

**Comment by GBKS** [comment]
There is a [dev PR](https://github.com/bitcoin-core/gui-qml/pull/343) for this task.

**Comment by GBKS** [comment]
I posted in the linked PR to ask how we can wrap up this issue. Seems like it just needs a final push.

**Comment by GBKS** [comment]
The linked PR is merged, so I think we can consider this task complete as well.
