### ISSUE TITLE
Please maintain both dark and light mode color definitions 

### ISSUE THREAD

**Issue by jarolrod** [BitcoinDesign/Bitcoin-Core-App#41]
Looking at the design system, The original basic color definitions were specified in both dark and light color modes:

| [dark](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=2643%3A83514&t=wsGoRsOW4dqQanKL-4) | [light](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=2643%3A83425&t=wsGoRsOW4dqQanKL-4) |
| ---- | ----- |
| ![Colors](https://user-images.githubusercontent.com/23396902/215311990-e912eb3f-abe1-48de-9253-1ad8c9dbef30.png) | ![Palette](https://user-images.githubusercontent.com/23396902/215312015-5f07af5a-0dac-49fb-9e7f-263015366bdb.png) |

But, we don't currently maintain this for the new colors that have been added such as in relation to [Button Variations and States](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=2643%3A83779&t=wsGoRsOW4dqQanKL-4) and the [Block Clock Confirmation Colors](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=5954%3A1007232&t=wsGoRsOW4dqQanKL-4)

**Comment by GBKS** [comment]
I added these (primary shades and confirmations) in Figma and [the website](https://bitcoincore.app/colors/). They are currently the same for light and dark modes. They work pretty well, but I'd like to come back at some point after V1 launch to see if we want to tweak them a bit.
