### ISSUE TITLE
Subtle animation on "Estimating" state

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#48]
This block clock state can feel like it's unresponsive because you might see it for minutes and there's no motion at all. 

![Frame 156](https://user-images.githubusercontent.com/695901/232453292-6f315c19-1ca7-40f0-ac87-5834cdcafb42.jpg)

If the text "Estimating" subtly changes color (like from neutral 7 to neutral 5 and back), it might feel a bit more like something is actually happening. This could also work well for the "0%" text. If we're not even at "0.01%", a subtle animation (neutral 9 to 7) would help communicate that something is happening.

What do you think?

**Comment by jarolrod** [comment]
Addressed by https://github.com/bitcoin-core/gui-qml/pull/325

**Comment by jarolrod** [comment]
Closing as this was done already
