### ISSUE TITLE
Inconsistent design language on settings page titles 

### ISSUE THREAD

**Issue by jarolrod** [BitcoinDesign/Bitcoin-Core-App#55]
Original settings pages were implemented to have the page title on the page content itself, while new settings pages we're adding like Display settings have the page title in the navbar. This seems like an inconsistent design language.

| content page title | navbar page title |
| ------------------ | ----------------- |
| <img width="752" alt="settings-page-breakdown" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/23396902/9ebb1053-8d1d-4ac5-88b0-efe42e2c5cd4"> | <img width="752" alt="navbar-setting-title" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/23396902/1f28aa50-0c85-4355-a597-aa34e640180d"> |

**Comment by GBKS** [comment]
The original settings screens are part of onboarding, where we make things a little simpler, bigger and more visual. Later, when you're in settings, we want functional and are OK with a bit more complexity. When onboarding screens also get re-used later in settings, things get a bit mixed up. Which screens are currently re-used?

**Comment by jarolrod** [comment]
We can have a bool that essentially switches the main title from the content into the navbar

**Comment by GBKS** [comment]
That works! Do you need anything design-wise for this?

**Comment by GBKS** [comment]
Can we resolve this one? Anything else to clarify here?
