### ISSUE TITLE
Design specs for the desktop top bar component

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#57]
In yesterday's call, we reviewed the current draft of the updated nav structure for when we have all the wallet features. An important element of this is the top bar on the desktop. Let's spec out all the different states in detail.

From the current design draft:

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/1f2fa562-2f87-4448-8cb8-c52b1437dc37)

Older designs which show a lot of different states, but have a dedicated wallet page which we don't want anymore.

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/d403d091-8aa5-43c3-8daf-57d545513aef)

Jarol had also asked us to mock-up the hover, selected, disabled, focus and any other states needed. Those should be pretty straightforward now since we have our standard treatments defined.

**Comment by stackingsaunter** [comment]
Let me work on this one

**Comment by stackingsaunter** [comment]
Here's what I've done so far - [Figma file](https://www.figma.com/file/KHPJ8SI2YEheEeTophLIhe/Bitcoin-Core-App-(Old)-(Jakub)?type=design&node-id=6942%3A124589&mode=design&t=YHTPRpXkrxO3aQaO-1)

I think I covered them all, next steps would be to do wallet selector and it's states.
Not sure if wallet selector "active" should be white or orange.

I added "Yellow" (light/dark) color to use for node indicator.

I also used layout for the component and it's responsive (although for condesed state I had to change autolayout settings).

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/1e826bd3-5521-49e2-8104-36f1d7bb96b9)

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/ba71139d-b46a-486b-aacf-02bf712c988b)
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/a7570f36-2d19-4a3b-8c21-ba3a97e35ce5)
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/38975c67-e139-4b4c-83dc-0ec74d49d079)
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/b5e24f7b-47d7-40bc-90d2-b8f47c34c84e)
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/f064dd5a-6de0-40f6-a43c-0c2d7fb57022)

**Comment by yashrajd** [comment]
Regarding nav item states discussed today – below are screenshots from v1.0:

- back button: icon, label are white in active state
- (see cursor) Hovering changes label to Orange from white

<img width="641" alt="Screenshot 2023-07-12 at 16 31 56" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/114083781/a3d24651-b572-4bae-9afe-8f2b6ec6ebb7">

Also currently, Hover state for the Back button puts it in a grey box (see below). We could also try something like that here.

<img width="644" alt="Screenshot 2023-07-12 at 16 43 33" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/114083781/14a07d27-8109-421e-a2cd-d074aa5f379e">

**Comment by stackingsaunter** [comment]
Did some updates.

Two layouts of wallet selector/balance and 2 types of color states. But I just realised the one with grey box @yashrajd proposed can be also nice, I can try this one as well.

<img width="775" alt="image" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/b0c1f853-94dd-4805-b4f2-9a67947727fb">

<img width="834" alt="image" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/3ecf179d-65cc-4deb-bb17-07bc17ad2d46">

<img width="716" alt="image" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/ed0eb46e-9ad5-4aec-8a77-9236808c1de9">

<img width="959" alt="image" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/fc73d1b9-5007-4463-a24c-ecb84e5d3959">

You can try the prototype [here](https://www.figma.com/proto/KHPJ8SI2YEheEeTophLIhe/Bitcoin-Core-App-(Old)-(Jakub)?page-id=6942%3A124589&type=design&node-id=6942-162890&viewport=-428%2C1790%2C0.33&t=IDunFe34KGkBYHpM-1&scaling=min-zoom&starting-point-node-id=6942%3A162890&show-proto-sidebar=1&mode=design)

I also added "pressed" state. Another idea for hover could perhaps be similar but darker

<img width="1456" alt="image" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/de916125-fce9-4b5a-9435-cd4a43cd12c8">

**Comment by stackingsaunter** [comment]
Haven't spend much time on mobile, but sketched out some initial ideas

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/e4623940-ff8d-46b6-8d28-4bacff2ada0d)

**Comment by yashrajd** [comment]
Prototype's cool & very helpful @stackingsaunter.

I'm conflicted about Hover state: grey box will maintain consistency with existing behaviour (like Back button already implemented) but orange is fine too.

I'm agnostic about a Pressed state, but if implemented I prefer it as implemented in the prototype (orange + grey box, which makes sense since you need to hover before pressing) instead of the white in grey box as in your image above. 

So here's my view (for dark mode) so far:
- inactive: white
- hover: grey box
- pressed: orange + grey box (orange signifies it will become active when action is completed)
- active: Orange with underline (as Christoph proposed)

- disabled: grey/dark grey

----------
For wallet selector/balance, I prefer white labels instead of grey. Unsure about icon since it means we have to provide options + extra UI to choose but perhaps we could do it in the future. Emoji set might be an easy way to go.

**Comment by GBKS** [comment]
Thank you for all the work on this, makes it super easy to compare options. I prefer the more subtle one with light grey text. It uses our color palette in a nicer way, IMHO. Having a very light transition duration of 100-150ms will also make it just a little bit nicer.

For toggling between balance display, we could also rely on the shift key. So shift-click to switch between full bitcoin (0.01 000 000), trimmed bitcoin (0.01), sats (10,000,000), and maybe even hidden balance. That would be in addition to having a toggle elsewhere, like the application menu bar and settings.

I looked into the wallet icon a bit more. It would be cool if those could represent different types, so here are some ideas.

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/7cac5314-f1f1-4d8b-abc3-9ce89fb9f630)

If we have a good hover state, maybe we don't need the small arrow to indicate the switcher?

**Comment by GBKS** [comment]
For mobile, I'd keep send and receive as tabs since those are primary options (compared to block clock and settings) and tabs are easy to reach on mobile. It also solves the privacy issue of exposing your balance when you want to just do a quick send/receive.

**Comment by GBKS** [comment]
Brief note to also design a state for then the application is built without wallet features. The simplest approach is to remove the wallet icon/balance on the left and the tabs in the center, and only keep the block clock and settings buttons on the right.

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/4955e1fd-1be1-49f6-a5f0-c5f7c8da6a91)

**Comment by stackingsaunter** [comment]
Components are ready to review - [Figma file ](https://www.figma.com/file/KHPJ8SI2YEheEeTophLIhe/Bitcoin-Core-App---Jakub-workspace?type=design&node-id=6942-124589&mode=design&t=NAMfs1Rh4txO3OFr-0)

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/5a8c11c9-bab2-4053-803a-0bf52db56631)
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/0235a6b0-16d0-42c2-ac41-771f15b23724)
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/d8957247-fe48-4f82-b1a8-9715279c187e)
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/d8cb8af1-730e-42e0-a172-9bdf496e18e8)
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/513204d1-5a2c-454f-bd23-51fe13e3646d)
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/2512d0b8-17bc-4e91-a35f-756a14e92564)


Current mobile design oscillates around those 4 ideas. More work to be done here
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/9f47d040-93d5-4f0f-906f-277b817f9623)

**Comment by stackingsaunter** [comment]
@GBKS did you end up deciding on mobile direction while I was gone?

**Comment by GBKS** [comment]
[Here's the latest](https://bitcoincore.app/milestones/1-2-navigation/) (if I remember correctly.

It might be nice to put together a web prototype for some of this stuff, so we can quickly feel it out and iterate.

**Comment by stackingsaunter** [comment]
After some thought, I propose this screen as main mobile nav:

![CleanShot 2024-01-17 at 14 54 45@2x](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/389f530c-89eb-4eb1-b4be-498e6c751627)


My reasoning:

- "Settings" on desktop is not equal item to Activity, Send and Receive, so I think it's more consistent if it's not on mobile as well
- (Assumption) In most cases, especially on mobile, users will not visit "Settings" often so it does not need to be as handy in the bottom nav as other options
- As for wallet list dropdown, I chose this as it's exactly the same as on desktop, so to keep things simple and consistent 


Alternitavely, wallet selector could be wider for easier selection 

![CleanShot 2024-01-17 at 14 56 12@2x](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/fe8e7845-5f5d-4db7-b4f8-fd353e3c2f0e)

**Comment by stackingsaunter** [comment]
I think this can be closed, as we agreed on the layout and you @GBKS updated the main file already. This is the mobile design we ended up with:

![CleanShot 2024-02-20 at 22 49 13@2x](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/66c3771b-e13e-4034-aecd-ac206d1dd9aa)

**Comment by GBKS** [comment]
Looks like I need to update a few minor things on the design docs still.

Also spoke with @johnny9 yesterday about the wallet list. He's going to look into what information we have about closed wallets. Might be easiest for now to just design three options where we just have the name, name + type, and name + type + balance, and then use whichever one we can make work technically.

**Comment by johnny9** [comment]
> Also spoke with @johnny9 yesterday about the wallet list. He's going to look into what information we have about closed wallets. 

It looks like you only know the name of the wallet folder if the wallet is closed. When the wallet is open you know all of the other values. From my understanding, I think the UX can be modified for the new UI and attempt to load the wallets for these values unless they were previously closed. If they are closed, persist that in the settings. Regardless, we do need to have a clear "closed" state for the wallet selector.

**Comment by GBKS** [comment]
Closing this general issue, as I think we have it well covered [in the docs](https://bitcoincore.app/milestones/1-2-navigation/). If there are minor tweaks required, we can create new issues.
