### ISSUE TITLE
Widgets?

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#6]
The center of the app is the block clock. We could allow users to add 1-2 widgets below the block clock to display information about the node activity they find interesting.

Initial node widget explorations.
<img width="826" alt="Bitcoin Core App prototype widgets 210914" src="https://user-images.githubusercontent.com/695901/135259751-3187f5b3-dadc-4285-88df-d66c3315849b.png">

**Comment by jarolrod** [comment]
i like widgets :D

**Comment by GBKS** [comment]
This idea is captured in the [Showcase page](https://bitcoincore.app/showcase/) on the design docs. Going to close this issue, and we can open up new ones that are more specific.
