### ISSUE TITLE
Download a snapshot for mobile nodes

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Bitcoin-Core-App#7]
As apps can not run in the background on mobile the IBD is likely going to take a very long time to complete on mobile. A possible solution for this is to have a snapshot download from a trusted source (devs who make the app?) as to bootstrap the IBD. 

Of course the users should be able to turn this off if they wish but if this were to be an option I would think having it as the default would be best.

Here is an example of a snapshot you can download and get Bitcoin Core IBD completed within minutes: https://prunednode.today/

**Comment by jarolrod** [comment]
This is not something we're going to promote with Core. It's not secure in any way and just a bad idea. You're running the node to audit the network and verify your transactions.
