### ISSUE TITLE
Design the peer details screen

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#78]
The [peers screen](https://bitcoincore.app/settings/#peers) is working great, and it's time to design and implement the peer details screen, which shows all the information and options of a single peer.

Here's a first design ([Figma](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App-(Old)?type=design&node-id=7145%3A7019&mode=design&t=eEr3sGiGhf2f98Cr-1)).

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/ffd08986-84ca-4b27-bb24-937ddb2c537b)

And the original design from the current GUI.

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/89253c11-98cf-43b7-8408-e0240fb007f7)

The new design tries to order the data fields into logical groupings, and treat each data point uniquely for clearer communication. Goal is that users can more easily scan the page, find what they are looking for, and interpret the data correctly.

The colored dots indicate a relative value compared to other peers. A green dot means that this peers value is "the best" compared to the values of other peers. Read means it's the worst. Mix the colors for in-betweens. We use relative indicators because it's not really possible to establish globally applicable benchmarks.

The values might also benefit from tooltips to provide a bit more information. I am curious how else we could improve the data visualization.

**Comment by BitBrujo** [comment]
This looks good. Should we indicate wether it is a full relay vs a block relay on this screen, or just assume that the info is learned from the selected tab?

**Comment by GBKS** [comment]
Which data point indicates this?

**Comment by BitBrujo** [comment]
Full Relay and Block relay are the indicated "relay type" on the original design from the current GUI, when you select the peer on the left side colum.

**Comment by GBKS** [comment]
Ah, looks like I forgot to add that in the design. Thanks for catching that.

**Comment by GBKS** [comment]
Minor update to include the type and indicators for the synced header and blocks values. I'll add this one to the design docs site as a first draft version that we can update as we go.

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/1d6e20f8-8458-4afd-a96d-3fdefb8517dc)

**Comment by GBKS** [comment]
Added to the design docs [here](https://bitcoincore.app/settings/#peers) via #86.

**Comment by GBKS** [comment]
We discussed this in the [call today](https://github.com/BitcoinDesign/Meta/issues/615), and there were some questions around banning. The design above is intended so that ban options are collapsed by default, as those are likely not commonly needed.

Also dug up a [StackOverflow link](https://bitcoin.stackexchange.com/questions/115183/why-would-i-need-to-ban-peer-nodes-in-bitcoin-network) that goes into the reasons for banning, and the [PR](https://github.com/bitcoin/bitcoin/pull/6158) that originally added the feature in 2015.

Currently, the feature is accessible in the QT GUI via right-clicking.
<img width="149" alt="image" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/7699702f-82ca-40bf-a1a3-c8311a5acca0">

@johnny9

**Comment by johnny9** [comment]
![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/985648/288a738c-4635-4ca4-b745-0d9fa7832faf)

This image potentially answers the question of where the banned peers appear. I'll try to run this myself to see more of the details.

**Comment by GBKS** [comment]
Thanks. It would make sense to see this second panel only once you actually have a ban in place. Gets quite crammed.

**Comment by GBKS** [comment]
Moved to a [separate page](https://bitcoincore.app/peers/) in the design docs so we have more space to lay out all the details (was previously in one huge settings page with all the other settings screens). Also changed/added:

- Small link at the bottom of the connected peers list to access banned peers
- Move ban time options into a modal/overlay/dialog (whatever you want to call it)
- Added screen that shows banned peers, each with an option to unban

@johnny9 what do you see missing still?

**Comment by johnny9** [comment]
> [@johnny9](https://github.com/johnny9) what do you see missing still?

The update looks really good.  I don't see anything major left.

**Comment by GBKS** [comment]
Awesome, then I will close this issue. The general design is done, and we can discuss details in separate issues.
