### ISSUE TITLE
Revisit use of fullscreen animation on desktop

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#80]
Concerns have been brought up that this causes a performance hit, probably especially on less capable computers and operating systems. So if you navigate from one screen to another, the previous screen might slide out to the left and the new screen might slide in from the right, stuttering along the way.

So far, we just kept everything consistent across desktop and mobile. On mobile, it is super common that screens slide in and out, as it creates an intuitive sense of hierarchy. It's less common on desktop. Some people are also sensitive to motion, which is why reducing motion is a common accessibility feature ([apple support page](https://support.apple.com/en-us/HT202655) and [CSS media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) examples).

That gives us a few questions:
- Can we support the accessibility feature?
- Is the performance hit real?
  - If so, do we disable these animations on desktop only?
  - If we do, is the navigation experience still intuitive or do we need to change anything else?

What do you think?

**Comment by jarolrod** [comment]
We can keep this up just in case its an issue in the future, but there really won't be any performance hit, and we should continue with out current approach with fullscreen animations.

**Comment by GBKS** [comment]
Added to the bottom of the [navigation page](https://bitcoincore.app/milestones/1-2-navigation/) in the design docs, so we can close this issue.
