### ISSUE TITLE
Revisit use of drawers and dialogs

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#81]
Some of the sub-screens we have are a bit sparse. One of the suggestions was to use a drawer on desktop instead of a full-screen navigation.

In this mock-up, we see a settings screen on the left. If the user clicks "Detailed settings", the middle screen slides up from below. The alternative would be to use a drawer instead, which is what the third screen shows.

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/52a10669-3133-4c5c-81e0-8b2f11c20733)

Considering the question of consistency, would we just always use a drawer or only if the screen is somewhat empty? We'd have to figure out a logic for that. If we sometime use full screens, and sometimes drawers, we'd have to ensure that the UI feels intuitive (predictable in this case).

Drawers exist as a mobile UI pattern, but are not very common. So far, we just kept everything consistent across desktop and mobile, for simplicity of design and coding. Because of this, I think it can be good to revisit some of the patterns as we keep working on the app. Especially as we start using it heavily, we may realize that some design choices did not pan out as we thought they would. For this specific one, it would be good not to make a change on the worst-case scenario (the most empty screen in the app), but all uses of this pattern, and take it from there.

**Comment by jarolrod** [comment]
@promag had opinions on this, but I personally don't think we need to rehash this, this can remain open just to serve as a pointer that this idea was considered, but I see nothing wrong with and prefer the approach we've been using

**Comment by GBKS** [comment]
Why don't we close this issue, so it's not clogging up our issue list? No one has brought this up since. If we want to keep a list of "considered ideas", we can track that somewhere else. For example, we have discussed keeping linking relevant issues and PRs in the respective pages of the design docs.

**Comment by GBKS** [comment]
Added to the bottom of the [navigation page](https://bitcoincore.app/milestones/1-2-navigation/) in the design docs, so we can close this issue.
