### ISSUE TITLE
Research section: Add content to Bitcoin Core App website

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Bitcoin-Core-App#87]
Various UX research efforts have been done on Bitcoin Core App as well as on the node side.

Opening this issue with a draft of content for a research section on the Bitcoin Core app website. Sharing the draft doc here which has the following headings:

- Intro to research
- Research efforts summary
- How research is organised
- Past research efforts
- How to contribute

Please feel free to have a [read through](https://docs.google.com/document/d/1IomulWV-cPBJ54T7VqCP56q0LmTsRwyHaqLjN_5cmUg/edit ) at the moment, just checking in if the structure provides enough context for someone who knows little about research and if the headings are suitable.

**Comment by mouxdesign** [comment]
Continued to work on the [write up:](https://docs.google.com/document/d/1IomulWV-cPBJ54T7VqCP56q0LmTsRwyHaqLjN_5cmUg/edit?usp=sharing)
- Added in one image showing a high level overview of the research efforts done
- Improved the copy for readability


![Group 1 (18)](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/90313394/e7bb972d-2c19-4ff7-aed7-e4852809593c)

**Comment by GBKS** [comment]
The [research page](https://bitcoincore.app/research/) was added in #94. Can we close this issue?
