### ISSUE TITLE
Multi-window on desktop or not?

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Bitcoin-Core-App#9]
@promag asked if there are instances where we should pop out a new window on desktop, giving the use case of viewing two wallets at the same time. Let's discuss.

First, I think we should differentiate between modals/dialogs, overlays and application windows. I don't think there are clear naming conventions on these, so here's how I break it down:
- Modals/dialogs are often served by the OS with a simple question or alert and 1-2 buttons Cancel or OK an action. But I do think there's a case to be made to cover them in the application with custom UI when possible. It looks more consistent and doesn't mentally take you out of the application.
- Overlays temporarily cover some or all of the main window content. They contain more complex information that requires more complex formatting, may offer complex interactions, etc. Those are better handled in the application.
- Application windows: There's usually just one, and some use case benefit from multiple ones. For example, the Mail app creates a new window for writing an email. You can drag out tabs from a browser to see multiple sites next to each other. I think those needs to be really decided in context of the specific use case.

**Comment by Bosch-0** [comment]
For windows I think keep it all in the same window makes most sense. Things can get messy if a user is opening a new window each time they click on the wallet. In saying that though could always have a settings option within each wallet that says "Open wallet in new window" for those who want this view.

**Comment by jarolrod** [comment]
I'd say keep everything in one window. Later on maybe add the ability to move a visual element out into it's own window if users want that

**Comment by GBKS** [comment]
Considering the conversation has gone stale and that we are also building this for mobile, on which having multiple screens is not really an option, I'd suggest we table this. Going to close the issue for now.
