### ISSUE TITLE
Improve copy in language selector 

### ISSUE THREAD

**Issue by stackingsaunter** [BitcoinDesign/Bitcoin-Core-App#95]
We did a mistake showing country first in language selector, especially showing it when it's not necessary

![CleanShot 2024-01-24 at 14 16 02@2x](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/f6e03913-72a6-4bb6-a936-784af6ae2a78)

@GBKS proposed to follow how Apple does this:

![CleanShot 2024-01-24 at 14 17 54@2x](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/a7fe8fd5-d686-423e-8642-22345b1fd3c9)

So schema looks like this:

**Language name in the language itself (Region in the language itself)**
Language in device set language (Region in device set language)

We show regions only when it's needed, so when we have regional translations for the same language

Another acceptable idea is to just use native language, without device set language, but showing regions where needed:

![CleanShot 2024-01-24 at 14 21 55@2x](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/68239231/d89ed48f-9489-4f3c-aad7-eaf8f5f36901)

Yashraj also asked If we can detect machine language and set it automatically at the run of GUI. That would be the best I think, but still I think we should change the selector to one of the designs above^

**Comment by GBKS** [comment]
<img width="850" alt="Bitcoin Core App language picker 220125" src="https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/e2e319c8-c40d-414b-a233-bf26ab45846b">

Here's a small update with two layout variations and an added search.

Looking at the basics, the language is always shown in the language itself, and in the currently selected language. The country is only shown to distinguish dialects across countries.

I prefer the horizontal layout as it's more compact and easy to scroll through - this list can be pretty long. For the same reason, I added in a quick search at the top. Additionally, a user should be able to press any keyboard character and the list should scroll to the first language that starts with that character. Obviously works better for some languages than others.

**Comment by stackingsaunter** [comment]
+1 for horizontal with search, +10 for keyboard live search

**Comment by GBKS** [comment]
I just updated the design docs page, this language picker is covered in [display settings](https://bitcoincore.app/settings/display/). One thing missing is whether we use the same dropdown on mobile, or go with a full-screen list (probably the latter).

@stackingsaunter can you maybe do a quick review and see if anything is missing, so we can then close out this issue?

**Comment by GBKS** [comment]
Here are the designs with the drawer version for mobile. I also updated the [design docs](https://bitcoincore.app/settings/display/). Let's call this one done for now, and open up new issues if there are tweaks.

![image](https://github.com/BitcoinDesign/Bitcoin-Core-App/assets/695901/08423342-bb3c-464f-a7e7-4ad0bb01340f)
